## Logistic Regression Workshop

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

df=pd.read_csv('iris-data-clean.csv')

df.head()

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm   class
0              5.1             3.5              1.4             0.2  Setosa
1              4.9             3.0              1.4             0.2  Setosa
2              4.7             3.2              1.3             0.2  Setosa
3              4.6             3.1              1.5             0.2  Setosa
4              5.0             3.6              1.4             0.2  Setosa

In [15]:

encode=LabelEncoder()
df['class']=encode.fit_transform(df['class'])
df.head()

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  class
0              5.1             3.5              1.4             0.2      0
1              4.9             3.0              1.4             0.2      0
2              4.7             3.2              1.3             0.2      0
3              4.6             3.1              1.5             0.2      0
4              5.0             3.6              1.4             0.2      0

In [16]:
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

logistic=LogisticRegression()
x=df[['sepal_length_cm','sepal_width_cm','petal_length_cm','petal_width_cm']]
y=df['class']


x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
logistic.fit(x_train, y_train)

y_pre=logistic.predict(x_test)
accuracy_score(y_test,y_pre)
print(confusion_matrix(y_test,y_pre))

[[ 8  0  0]
 [ 0  9  1]
 [ 0  1 10]]


In [18]:
x_sepal_length=df[['sepal_length_cm']]
x_sepal_width=df[['sepal_width_cm']]
logistic_length = LogisticRegression()
logistic_width = LogisticRegression()

logistic_length.fit(x_sepal_length, y)
logistic_width.fit(x_sepal_width, y)

y_pre_length = logistic_length.predict(x_sepal_length)
y_pre_width = logistic_width.predict(x_sepal_width)

print("Accuracy using sepal length only:", accuracy_score(y, y_pre_length))
print("Accuracy using sepal width only:", accuracy_score(y, y_pre_width))

Accuracy using sepal length only: 0.7379310344827587
Accuracy using sepal width only: 0.5517241379310345
